#!/usr/bin/env sh
TOP_LEVEL=$(git rev-parse --show-toplevel)
HOOKS="applypatch-msg pre-applypatch post-applypatch pre-commit prepare-commit-msg commit-msg post-commit pre-rebase post-checkout post-merge pre-receive update post-receive post-update pre-auto-gc"
# assuming the script is in a bin directory, one level into the repo
HOOKS_DIR=$TOP_LEVEL/.git/hooks

for hook in $HOOKS; do
	# If the hook already exists, is executable, and is not a symlink
	if [ ! -h "$HOOKS_DIR/$hook" -a -x "$HOOKS_DIR/$hook" ]; then
		mv "$HOOKS_DIR/$hook" "$HOOKS_DIR/$hook.user"
	fi
	# create the symlink, overwriting the file if it exists
	# probably the only way this would happen is if you're using an old version of git
	# -- back when the sample hooks were not executable, instead of being named ____.sample
	ln -s -f "$TOP_LEVEL/githooks/wrapper" "$HOOKS_DIR/$hook"
done