#!/usr/bin/env sh

# Only staged files
files=$(git diff --cached --name-only --diff-filter=ACM | grep "^data/AX[0-9A-F]\+\.md$")

if [ "$files" = "" ]; then
	exit 0
fi

mode=100644
for file in ${files}; do
	#./axlint < ./$file > ./$file
	# read staged file content
	echo "lint $file"
	# Get staged file, lint it, then update the git index
	# Based on:
	# https://gist.github.com/ihower/6132576
	# http://eddmann.com/posts/the-internals-of-git/
	hash=$(git cat-file blob ":$file" | ./axlint | git hash-object -w --stdin)
	git update-index --add --cacheinfo $mode $hash "$file"
done